/*
 * Merchants Locations API
 * Merchants Locations API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.merchants.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mastercard.api.merchants.model.CountrySubdivision;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CountrySubdivisions
 */
public class CountrySubdivisionsTest {
    private final CountrySubdivisions model = new CountrySubdivisions();

    /**
     * Model tests for CountrySubdivisions
     */
    @Test
    public void testCountrySubdivisions() {
        // TODO: test CountrySubdivisions
    }

    /**
     * Test the property 'countrySubdivisions'
     */
    @Test
    public void countrySubdivisionsTest() {
        // TODO: test countrySubdivisions
    }

}
