/*
 * Merchants Locations API
 * Merchants Locations API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.merchants.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CountrySubdivision
 */
public class CountrySubdivisionTest {
    private final CountrySubdivision model = new CountrySubdivision();

    /**
     * Model tests for CountrySubdivision
     */
    @Test
    public void testCountrySubdivision() {
        // TODO: test CountrySubdivision
    }

    /**
     * Test the property 'countrySubdivisionCode'
     */
    @Test
    public void countrySubdivisionCodeTest() {
        // TODO: test countrySubdivisionCode
    }

    /**
     * Test the property 'countrySubdivisionName'
     */
    @Test
    public void countrySubdivisionNameTest() {
        // TODO: test countrySubdivisionName
    }

}
