/*
 * Merchants Locations API
 * Merchants Locations API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.merchants.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Merchant
 */
public class MerchantTest {
    private final Merchant model = new Merchant();

    /**
     * Model tests for Merchant
     */
    @Test
    public void testMerchant() {
        // TODO: test Merchant
    }

    /**
     * Test the property 'addressLine1'
     */
    @Test
    public void addressLine1Test() {
        // TODO: test addressLine1
    }

    /**
     * Test the property 'addressLine2'
     */
    @Test
    public void addressLine2Test() {
        // TODO: test addressLine2
    }

    /**
     * Test the property 'cashbackMaximumAmount'
     */
    @Test
    public void cashbackMaximumAmountTest() {
        // TODO: test cashbackMaximumAmount
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'countryName'
     */
    @Test
    public void countryNameTest() {
        // TODO: test countryName
    }

    /**
     * Test the property 'countrySubdivisionCode'
     */
    @Test
    public void countrySubdivisionCodeTest() {
        // TODO: test countrySubdivisionCode
    }

    /**
     * Test the property 'countrySubdivisionName'
     */
    @Test
    public void countrySubdivisionNameTest() {
        // TODO: test countrySubdivisionName
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'distance'
     */
    @Test
    public void distanceTest() {
        // TODO: test distance
    }

    /**
     * Test the property 'distanceUnit'
     */
    @Test
    public void distanceUnitTest() {
        // TODO: test distanceUnit
    }

    /**
     * Test the property 'easySavingsMerchantOfferId'
     */
    @Test
    public void easySavingsMerchantOfferIdTest() {
        // TODO: test easySavingsMerchantOfferId
    }

    /**
     * Test the property 'geocodingResult'
     */
    @Test
    public void geocodingResultTest() {
        // TODO: test geocodingResult
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'isPayPassConcession'
     */
    @Test
    public void isPayPassConcessionTest() {
        // TODO: test isPayPassConcession
    }

    /**
     * Test the property 'isPayPassPharmacy'
     */
    @Test
    public void isPayPassPharmacyTest() {
        // TODO: test isPayPassPharmacy
    }

    /**
     * Test the property 'isPayPassFuelPump'
     */
    @Test
    public void isPayPassFuelPumpTest() {
        // TODO: test isPayPassFuelPump
    }

    /**
     * Test the property 'isPayPassTollBooth'
     */
    @Test
    public void isPayPassTollBoothTest() {
        // TODO: test isPayPassTollBooth
    }

    /**
     * Test the property 'isPayPassDriveThrough'
     */
    @Test
    public void isPayPassDriveThroughTest() {
        // TODO: test isPayPassDriveThrough
    }

    /**
     * Test the property 'isPayPassRegister'
     */
    @Test
    public void isPayPassRegisterTest() {
        // TODO: test isPayPassRegister
    }

    /**
     * Test the property 'isPayPassTicketing'
     */
    @Test
    public void isPayPassTicketingTest() {
        // TODO: test isPayPassTicketing
    }

    /**
     * Test the property 'isPayPassVendingMachine'
     */
    @Test
    public void isPayPassVendingMachineTest() {
        // TODO: test isPayPassVendingMachine
    }

    /**
     * Test the property 'isRepowerByCardSwipeSupported'
     */
    @Test
    public void isRepowerByCardSwipeSupportedTest() {
        // TODO: test isRepowerByCardSwipeSupported
    }

    /**
     * Test the property 'isRepowerByMoneyPakSupported'
     */
    @Test
    public void isRepowerByMoneyPakSupportedTest() {
        // TODO: test isRepowerByMoneyPakSupported
    }

    /**
     * Test the property 'latitude'
     */
    @Test
    public void latitudeTest() {
        // TODO: test latitude
    }

    /**
     * Test the property 'locationName'
     */
    @Test
    public void locationNameTest() {
        // TODO: test locationName
    }

    /**
     * Test the property 'longitude'
     */
    @Test
    public void longitudeTest() {
        // TODO: test longitude
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'websiteUrl'
     */
    @Test
    public void websiteUrlTest() {
        // TODO: test websiteUrl
    }

}
