/*
 * Merchants Locations API
 * Merchants Locations API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.merchants.client;

import com.mastercard.api.merchants.ApiClient;
import com.mastercard.api.merchants.ApiException;
import com.mastercard.api.merchants.model.Categories;
import com.mastercard.developer.interceptors.OkHttpOAuth1Interceptor;
import com.mastercard.developer.utils.AuthenticationUtils;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;

import java.security.PrivateKey;

/**
 * API tests for CategoriesApi
 */
@Ignore
public class CategoriesApiTest {

    private ApiClient client;
    private PrivateKey signingKey;
    private final CategoriesApi api = new CategoriesApi();

    private static final String BASE_URL = "https://sandbox.api.mastercard.com/locations/merchants";
    private static final String CONSUMER_KEY = "yourconsumerkeystring";
    private static final String PKCS_12_KEY_FILE_PATH = "./path/to/your/signing-key.p12";
    private static final String SIGNIN_KEY_ALIAS = "yourkeyalias";
    private static final String SIGNIN_KEY_PASSWORD = "yourpassword";


    @Before
    public void setUp() throws Exception {
        signingKey = AuthenticationUtils.loadSigningKey(PKCS_12_KEY_FILE_PATH, SIGNIN_KEY_ALIAS, SIGNIN_KEY_PASSWORD);

        client = new ApiClient();
        client.setBasePath(BASE_URL);
        client.setConnectTimeout(60);
        client.setDebugging(true);
        client.setHttpClient(client
                .getHttpClient()
                .newBuilder()
                .addInterceptor(new OkHttpOAuth1Interceptor(CONSUMER_KEY, signingKey))
                .build()
        );

        api.setApiClient(client);
    }


    /**
     * Get a list of merchant categories
     *
     * Returns a list of merchant categories
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMerchantCategoriesTest() throws ApiException {
        Categories response = api.getMerchantCategories();

        Integer expectedOffset =  0;
        Assert.assertTrue("0",response.getCategories().size() > 0);
        Assert.assertNotNull(response.getCategories().get(0).getCategoryId());
        Assert.assertNotNull(response.getCategories().get(0).getCategoryName());
    }
    
}
