/*
 * Merchants Locations API
 * Merchants Locations API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.merchants.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mastercard.api.merchants.model.CountrySubdivision;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * List of country subdivisions
 */
@ApiModel(description = "List of country subdivisions")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-04T16:00:00.598858300-05:00[America/Chicago]")
public class CountrySubdivisions {
  public static final String SERIALIZED_NAME_COUNTRY_SUBDIVISIONS = "countrySubdivisions";
  @SerializedName(SERIALIZED_NAME_COUNTRY_SUBDIVISIONS)
  private List<CountrySubdivision> countrySubdivisions = null;


  public CountrySubdivisions countrySubdivisions(List<CountrySubdivision> countrySubdivisions) {
    
    this.countrySubdivisions = countrySubdivisions;
    return this;
  }

  public CountrySubdivisions addCountrySubdivisionsItem(CountrySubdivision countrySubdivisionsItem) {
    if (this.countrySubdivisions == null) {
      this.countrySubdivisions = new ArrayList<CountrySubdivision>();
    }
    this.countrySubdivisions.add(countrySubdivisionsItem);
    return this;
  }

   /**
   * countrySubdivisions
   * @return countrySubdivisions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[{\"countrySubdivisionName\":\"Alabama\",\"countrySubdivisionCode\":\"AL\"}]", value = "countrySubdivisions")

  public List<CountrySubdivision> getCountrySubdivisions() {
    return countrySubdivisions;
  }


  public void setCountrySubdivisions(List<CountrySubdivision> countrySubdivisions) {
    this.countrySubdivisions = countrySubdivisions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CountrySubdivisions countrySubdivisions = (CountrySubdivisions) o;
    return Objects.equals(this.countrySubdivisions, countrySubdivisions.countrySubdivisions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countrySubdivisions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CountrySubdivisions {\n");
    sb.append("    countrySubdivisions: ").append(toIndentedString(countrySubdivisions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

