/*
 * Merchants Locations API
 * Merchants Locations API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.merchants.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mastercard.api.merchants.model.Merchant;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Merchants
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-04T16:00:00.598858300-05:00[America/Chicago]")
public class Merchants {
  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  private Integer count;

  public static final String SERIALIZED_NAME_LIMIT = "limit";
  @SerializedName(SERIALIZED_NAME_LIMIT)
  private Integer limit;

  public static final String SERIALIZED_NAME_OFFSET = "offset";
  @SerializedName(SERIALIZED_NAME_OFFSET)
  private Integer offset;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private Integer total;

  public static final String SERIALIZED_NAME_MERCHANTS = "merchants";
  @SerializedName(SERIALIZED_NAME_MERCHANTS)
  private List<Merchant> merchants = null;


  public Merchants count(Integer count) {
    
    this.count = count;
    return this;
  }

   /**
   * The number of items in the retrieved data set
   * @return count
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10", value = "The number of items in the retrieved data set")

  public Integer getCount() {
    return count;
  }


  public void setCount(Integer count) {
    this.count = count;
  }


  public Merchants limit(Integer limit) {
    
    this.limit = limit;
    return this;
  }

   /**
   * The number of items requested to be retrieved
   * @return limit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10", value = "The number of items requested to be retrieved")

  public Integer getLimit() {
    return limit;
  }


  public void setLimit(Integer limit) {
    this.limit = limit;
  }


  public Merchants offset(Integer offset) {
    
    this.offset = offset;
    return this;
  }

   /**
   * The page offset used for the query
   * @return offset
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "The page offset used for the query")

  public Integer getOffset() {
    return offset;
  }


  public void setOffset(Integer offset) {
    this.offset = offset;
  }


  public Merchants total(Integer total) {
    
    this.total = total;
    return this;
  }

   /**
   * The total number of merchants available to be retrieved
   * @return total
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "210", value = "The total number of merchants available to be retrieved")

  public Integer getTotal() {
    return total;
  }


  public void setTotal(Integer total) {
    this.total = total;
  }


  public Merchants merchants(List<Merchant> merchants) {
    
    this.merchants = merchants;
    return this;
  }

  public Merchants addMerchantsItem(Merchant merchantsItem) {
    if (this.merchants == null) {
      this.merchants = new ArrayList<Merchant>();
    }
    this.merchants.add(merchantsItem);
    return this;
  }

   /**
   * The list of merchants retrieved
   * @return merchants
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The list of merchants retrieved")

  public List<Merchant> getMerchants() {
    return merchants;
  }


  public void setMerchants(List<Merchant> merchants) {
    this.merchants = merchants;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Merchants merchants = (Merchants) o;
    return Objects.equals(this.count, merchants.count) &&
        Objects.equals(this.limit, merchants.limit) &&
        Objects.equals(this.offset, merchants.offset) &&
        Objects.equals(this.total, merchants.total) &&
        Objects.equals(this.merchants, merchants.merchants);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, limit, offset, total, merchants);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Merchants {\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    merchants: ").append(toIndentedString(merchants)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

